export type Platform = 'youtube' | 'instagram';
export type ContentStatus = 'idea' | 'draft' | 'scheduled' | 'published';
export type ContentType = 'video' | 'short' | 'reel' | 'carousel' | 'post' | 'tutorial';

export interface CalendarContent {
  id: string;
  title: string;
  platform: Platform;
  type: ContentType;
  status: ContentStatus;
  scheduledDate: string; // YYYY-MM-DD
  scheduledTime: string; // HH:MM
  wordCount?: number;
  aiAssisted: boolean;
  tags: string[];
  notes?: string;
}

export const allContent: CalendarContent[] = [
  // Published
  {
    id: 'content-001',
    title: 'My 2026 Camera Gear Guide — Everything I Use',
    platform: 'youtube',
    type: 'video',
    status: 'published',
    scheduledDate: '2026-09-01',
    scheduledTime: '14:00',
    wordCount: 3200,
    aiAssisted: true,
    tags: ['gear', 'youtube', 'camera'],
  },
  {
    id: 'content-002',
    title: 'Morning routine of a full-time creator',
    platform: 'instagram',
    type: 'reel',
    status: 'published',
    scheduledDate: '2026-09-01',
    scheduledTime: '10:00',
    wordCount: 180,
    aiAssisted: false,
    tags: ['lifestyle', 'creator'],
  },
  {
    id: 'content-003',
    title: 'Figma Shortcuts You\'re Missing in 2026',
    platform: 'instagram',
    type: 'carousel',
    status: 'published',
    scheduledDate: '2026-09-03',
    scheduledTime: '11:00',
    wordCount: 420,
    aiAssisted: true,
    tags: ['design', 'figma', 'tools'],
  },
  {
    id: 'content-004',
    title: 'How I Batch Record 4 Videos in One Day',
    platform: 'youtube',
    type: 'tutorial',
    status: 'published',
    scheduledDate: '2026-09-04',
    scheduledTime: '15:00',
    wordCount: 2800,
    aiAssisted: true,
    tags: ['productivity', 'youtube', 'batching'],
  },
  // Scheduled
  {
    id: 'content-005',
    title: 'How I Automated My Entire YouTube Workflow with AI',
    platform: 'youtube',
    type: 'video',
    status: 'scheduled',
    scheduledDate: '2026-09-06',
    scheduledTime: '14:00',
    wordCount: 3400,
    aiAssisted: true,
    tags: ['ai', 'workflow', 'youtube'],
    notes: 'Thumbnail ready. Script approved.',
  },
  {
    id: 'content-006',
    title: 'Tools I use to edit Reels in under 20 minutes',
    platform: 'instagram',
    type: 'reel',
    status: 'scheduled',
    scheduledDate: '2026-09-08',
    scheduledTime: '11:00',
    wordCount: 220,
    aiAssisted: true,
    tags: ['editing', 'reels', 'tools'],
  },
  {
    id: 'content-007',
    title: 'Notion for Creators — Full Walkthrough',
    platform: 'youtube',
    type: 'tutorial',
    status: 'scheduled',
    scheduledDate: '2026-09-10',
    scheduledTime: '15:00',
    wordCount: 2900,
    aiAssisted: false,
    tags: ['notion', 'productivity', 'creators'],
  },
  {
    id: 'content-008',
    title: '5 VS Code Extensions That Made Me 3x Faster',
    platform: 'youtube',
    type: 'video',
    status: 'scheduled',
    scheduledDate: '2026-09-13',
    scheduledTime: '14:00',
    wordCount: 2600,
    aiAssisted: true,
    tags: ['vscode', 'dev', 'productivity'],
  },
  {
    id: 'content-009',
    title: 'Behind the scenes — my editing process',
    platform: 'instagram',
    type: 'carousel',
    status: 'scheduled',
    scheduledDate: '2026-09-15',
    scheduledTime: '10:00',
    wordCount: 380,
    aiAssisted: false,
    tags: ['bts', 'editing', 'creator'],
  },
  {
    id: 'content-010',
    title: 'Why I quit using Premiere Pro after 5 years',
    platform: 'youtube',
    type: 'video',
    status: 'scheduled',
    scheduledDate: '2026-09-17',
    scheduledTime: '14:00',
    wordCount: 3100,
    aiAssisted: true,
    tags: ['editing', 'opinion', 'youtube'],
  },
  {
    id: 'content-011',
    title: 'Creator Toolkit 2026 — What\'s in my setup',
    platform: 'instagram',
    type: 'carousel',
    status: 'draft',
    scheduledDate: '2026-09-19',
    scheduledTime: '11:00',
    wordCount: 510,
    aiAssisted: true,
    tags: ['tools', 'setup', 'creator'],
  },
  {
    id: 'content-012',
    title: 'The algorithm change nobody is talking about',
    platform: 'youtube',
    type: 'video',
    status: 'scheduled',
    scheduledDate: '2026-09-20',
    scheduledTime: '14:00',
    wordCount: 2750,
    aiAssisted: true,
    tags: ['algorithm', 'youtube', 'strategy'],
  },
  {
    id: 'content-013',
    title: 'Day in my life as a full-time creator',
    platform: 'instagram',
    type: 'reel',
    status: 'draft',
    scheduledDate: '2026-09-22',
    scheduledTime: '10:00',
    wordCount: 200,
    aiAssisted: false,
    tags: ['lifestyle', 'creator', 'dayinlife'],
  },
  {
    id: 'content-014',
    title: 'Building a second brain for content creators',
    platform: 'youtube',
    type: 'tutorial',
    status: 'scheduled',
    scheduledDate: '2026-09-24',
    scheduledTime: '15:00',
    wordCount: 3300,
    aiAssisted: true,
    tags: ['pkm', 'notion', 'creators'],
  },
  {
    id: 'content-015',
    title: 'How I get 100K views on every video',
    platform: 'youtube',
    type: 'video',
    status: 'idea',
    scheduledDate: '2026-09-27',
    scheduledTime: '14:00',
    wordCount: 0,
    aiAssisted: false,
    tags: ['growth', 'youtube', 'strategy'],
  },
  {
    id: 'content-016',
    title: 'My honest review of CreatorOS after 30 days',
    platform: 'instagram',
    type: 'post',
    status: 'idea',
    scheduledDate: '2026-09-29',
    scheduledTime: '11:00',
    wordCount: 0,
    aiAssisted: false,
    tags: ['review', 'tools', 'creator'],
  },
];

// Unscheduled drafts (no confirmed date)
export const unscheduledDrafts: CalendarContent[] = [
  {
    id: 'draft-001',
    title: 'I used AI to plan my entire content month — here\'s what happened',
    platform: 'youtube',
    type: 'video',
    status: 'draft',
    scheduledDate: '',
    scheduledTime: '',
    wordCount: 1800,
    aiAssisted: true,
    tags: ['ai', 'experiment', 'creator'],
  },
  {
    id: 'draft-002',
    title: 'Reels editing tips for beginners',
    platform: 'instagram',
    type: 'reel',
    status: 'draft',
    scheduledDate: '',
    scheduledTime: '',
    wordCount: 290,
    aiAssisted: false,
    tags: ['reels', 'beginner', 'tips'],
  },
  {
    id: 'draft-003',
    title: 'My content strategy for Q4 2026',
    platform: 'youtube',
    type: 'video',
    status: 'draft',
    scheduledDate: '',
    scheduledTime: '',
    wordCount: 2100,
    aiAssisted: true,
    tags: ['strategy', 'q4', 'planning'],
  },
  {
    id: 'draft-004',
    title: 'Top 10 creator tools under $50',
    platform: 'instagram',
    type: 'carousel',
    status: 'draft',
    scheduledDate: '',
    scheduledTime: '',
    wordCount: 640,
    aiAssisted: true,
    tags: ['tools', 'budget', 'creator'],
  },
  {
    id: 'draft-005',
    title: 'How to grow from 0 to 10K subscribers',
    platform: 'youtube',
    type: 'tutorial',
    status: 'idea',
    scheduledDate: '',
    scheduledTime: '',
    wordCount: 0,
    aiAssisted: false,
    tags: ['growth', 'beginner', 'youtube'],
  },
];